<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Webir - Aktywacja konta</title>
</head>
<body>
<h1>Aktywacja konta</h1>
<p>Aby aktywawać konto w systemie Webir kliknij w poniższy link.</p>
<p><a href="<?php echo $this->serverUrl($this->url(array('hash'=>$this->hash),'activation'))?>"><?php echo $this->serverUrl($this->url(array('hash'=>$this->hash),'activation'))?></a></p>
</body>
</html>