<?php echo $this->partial('partials/subpage-navigation-main.phtml', array('userProcessCount' => $this->userProcessCount, 'active' => 'analysis-new')); ?>
<h1 id="analysisHeader">Analiza zaawansowana</h1>
<h3>Zestaw danych: <?php echo $this->data_set->name;?></h3>
<div><p><span class="icon-label fam-information" id="infoBar">Wybierz operację z poniższego menu.</span></p></div>
<div id="advancePanel"></div>