skrzynki(analysis_data$<?php echo $this->function->getVariables()->get(0)->index;?>,analysis_data$<?php echo $this->function->getVariables()->get(1)->index;?>, 
				etx="<?php echo $this->function->getParam('etyx');?>", ety="<?php echo $this->function->getParam('etyy');?>", wielkosc=<?php echo $this->function->getParam('size');?>, 
				dpi=<?php echo $this->function->getParam('dpi');?>, "<?php echo $this->function->getParam('chartPrefix');?>.png")
