#! /bin/sh
### BEGIN INIT INFO
# Provides:          webir
# Required-Start:    zend-server
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Uruchamia przetwarzanie zadan w Webir
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/zend/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
	if [ -x /home/httpd/scripts/webir.sh ]; then
		rm -f /tmp/webir_processing.lock
		rm -f /tmp/webir_manager.lock
		/home/httpd/scripts/restart-running-tasks.sh
		[ "$VERBOSE" != no ] && log_begin_msg "Running WebiR processing"
		sudo -i -u www-data -b /home/httpd/scripts/webir.sh
		ES=$?
		[ "$VERBOSE" != no ] && log_end_msg $ES
		return $ES
	fi
}

do_stop() {
		rm -f /tmp/webir_processing.lock
		rm -f /tmp/webir_manager.lock
    [ "$VERBOSE" != no ] && log_begin_msg "Stopping WebiR processing"
    PID=`ps ax | grep webir.sh | grep bash | cut -f 2 -d ' '`
    echo $PID
    kill -9 `echo $PID`
    killall -9 php
    killall -9 R
    [ "$VERBOSE" != no ] && log_end_msg $ES
    return 0
}

case "$1" in
    start)
	do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
	do_stop
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
